name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]
    paths:
      - '.github/workflows/docker-publish.yml'
      - '**.py'
      - 'web/**'
      - 'Dockerfile'
      - 'requirements.txt'
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main", "master" ]
    paths:
      - '.github/workflows/docker-publish.yml'
      - '**.py'
      - 'web/**'
      - 'Dockerfile'
      - 'requirements.txt'

jobs:
  build:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
    with:
      output: image
      push: ${{ github.event_name != 'pull_request' }}
      platforms: linux/amd64,linux/arm64
      runner: |
        default=ubuntu-24.04
        linux/amd64=ubuntu-24.04
        linux/arm64=ubuntu-24.04-arm
      setup-qemu: false
      cache: true
      cache-mode: max
      sign: 'false'
      meta-images: yushum/tg-uploader
      meta-tags: |
        type=raw,value=latest,enable={{is_default_branch}}
        type=ref,event=tag
    secrets:
      registry-auths: |
        - registry: docker.io
          username: yushum
          password: ${{ secrets.DOCKERHUB_TOKEN }}
